LABELS_DIRECTORY = './labels'
IMAGE_SIZE = 8
FEATURE_PLANES = 8
LABEL_SIZE = 4096
FILTERS = 128
HIDDEN = 512
CHECKPOINT_DIRECTORY = "slow_policy_checkpoint"
LOGDIR = LOGGING_DIRECTORY = "logdir"
TRAIN_DIRECTORY = './data_train'
VALIDATION_DIRECTORY = './data_validation'
BATCH_SIZE = 1280
NUM_STEPS = 150001
